stages:
  - install
  - test
  - build
  - deploy

# Cache dependencies to speed up subsequent jobs
cache:
  paths:
    - node_modules/

# Install dependencies
install_dependencies:
  stage: install
  image: node:18
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

# Build the app
build_app:
  stage: build
  image: node:18
  script:
    - npm run build
  artifacts:
    paths:
      - dist/ # Save build output